In [20]:
# python部分
#函数式编程小例子
nums = [1,2,5,0]
f = filter(lambda x: x>2,nums)
f

In [21]:
list(f)

[5]

In [9]:
#推荐列表解析
[i for i in nums if i>2]

[5]

In [18]:
#合并两个有序列表
def combine_sort(a,b):
    if a is None :
        return b
    if b is None:
        return a
    res = a[:]
    for ib in b:
        #对于b中的item，找到其在a中的位置
        for index,ia in enumerate(res[:]):
            if ib <= ia:
                res.insert(index,ib)
                break
            else:
                if index == len(res)-1:
                    res.append(ib)
                else:
                    continue
    return res
list1 = [42, 55, 56, 95, 123, 386]
list2 = [3, 5, 5, 8, 9, 11, 36, 56, 62, 88, 118, 211]
combine_sort(list1,list2)

[3, 5, 5, 8, 9, 11, 36, 42, 55, 56, 56, 62, 88, 95, 118, 123, 211, 386]

#### 实用库推荐
网络requests

时间日期处理arrow

### numpy基础

In [22]:

import numpy as np
lst = [[1,3,8],[2,4,7]]
arr = np.array(lst,dtype=float)
mat = np.mat(lst,dtype=float)
print('arr type:{}\nmat type:{}'.format(type(arr),type(mat)))
arr_add = arr + mat
print('\nType:{}\nValue:\n{}'.format(type(arr_add),arr_add))

arr type:<class 'numpy.ndarray'>
mat type:<class 'numpy.matrixlib.defmatrix.matrix'>

Type:<class 'numpy.matrixlib.defmatrix.matrix'>
Value:
[[  2.   6.  16.]
 [  4.   8.  14.]]


In [23]:
print ('ndim：',arr.ndim)
print ('shape：',arr.shape)
print ('size：',arr.size)
print ('dtype：',arr.dtype)
print ('itemsize：',arr.itemsize)


ndim： 2
shape： (2, 3)
size： 6
dtype： float64
itemsize： 8


In [41]:
ten = np.arange(10)
ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# 切片
ten[2:6]

array([2, 3, 4, 5])

In [45]:
#指定步长
ten[2:6:2]

array([2, 4])

In [50]:
ten.shape=(2,5)
#ten.reshape(2,5)
ten

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
ten[0]
ten[0,:]

array([0, 1, 2, 3, 4])

In [57]:
# 参数1为行，参数2为列
# 参数可以写成切片的形式，也可以写成数组形式
# 下面表示 第一行的2，3列
#ten[0,1:3]
#array([1, 2])
# 第一行的第三列和第二列
ten[0,[2,1]]

array([2, 1])

In [67]:
arr

array([[ 1.,  3.,  8.],
       [ 2.,  4.,  7.]])

In [68]:
#arr.reshape([1,6])
a1 = arr.reshape(1,6)
a1

array([[ 1.,  3.,  8.,  2.,  4.,  7.]])

In [76]:
a2 = arr.reshape(3,2)
# 效果等于 a2 = arr.reshape(3,-1)  其中-1表示不确定
a2

array([[ 1.,  3.],
       [ 8.,  2.],
       [ 4.,  7.]])

In [81]:
a3 = arr.reshape(6,1)
a3

array([[ 1.],
       [ 3.],
       [ 8.],
       [ 2.],
       [ 4.],
       [ 7.]])

In [84]:
# axis0轴从上到下
# axis1轴从左到右

#每一列的最小值
arr.min(axis=0)

array([ 1.,  3.,  7.])

In [85]:
#每一行的最大值
arr.max(axis=1)

array([ 8.,  7.])

In [89]:
#矩阵运算
new = np.mat([[4,5,8],[3,6,10]])
print('add:',arr + new)

add: [[  5.   8.  16.]
 [  5.  10.  17.]]


In [91]:
print('sub:',arr - new)

sub: [[-3. -2.  0.]
 [-1. -2. -3.]]


In [92]:
print('div:',arr / new)

div: [[ 0.25        0.6         1.        ]
 [ 0.66666667  0.66666667  0.7       ]]


In [94]:
arr2 = 2 * arr
arr2

array([[  2.,   6.,  16.],
       [  4.,   8.,  14.]])

In [96]:
# arr * arr2 默认数乘
np.multiply(arr,arr2)

array([[   2.,   18.,  128.],
       [   8.,   32.,   98.]])

In [97]:
arr.dot(arr2.T)

array([[ 148.,  140.],
       [ 140.,  138.]])

In [100]:
mat2 = mat * 2
mat2

matrix([[  2.,   6.,  16.],
        [  4.,   8.,  14.]])

In [101]:
# 矩阵数乘
np.multiply(mat,mat2)

matrix([[   2.,   18.,  128.],
        [   8.,   32.,   98.]])

In [104]:
#矩阵点乘
mat*mat2.transpose()
# mat.dot(mat2.transpose())


matrix([[ 148.,  140.],
        [ 140.,  138.]])

In [109]:
np.eye(3)
# 等价于 np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [107]:
np.eye(3,2)

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  0.]])

In [108]:
np.eye(2,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [113]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [114]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [115]:
np.linspace(1,10,3)

array([  1. ,   5.5,  10. ])

In [122]:
a = np.ones((2,2))
b = np.eye(2)

In [123]:
# 纵向合并
np.vstack((a,b))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  0.],
       [ 0.,  1.]])

In [121]:
# 横向合并
np.hstack((a,b))

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.]])

In [132]:
# 随机数
data = np.random.randn(2,3)
data

array([[-2.57823818, -1.4132194 , -0.0308894 ],
       [ 0.55458669, -0.29997222,  1.44522577]])

In [133]:
 # 统计 data 在[-5,-2.5,0,2.5,5.0]的分布
hist,edges = np.histogram(data,[-5,-2.5,0,2.5,5.0])
hist

array([1, 3, 2, 0])

In [137]:
import random
data2 = sorted(random.sample(range(100),6))
data2

[6, 18, 19, 38, 50, 54]

In [138]:
# 2在data2中的插入位置
np.searchsorted(data2,2)

0